import type { NextPage, GetStaticPaths, GetStaticProps } from "next";
import { ParsedUrlQuery } from "querystring";
import Head from "next/head";

import * as Utilities from "./../utilities";
import * as Components from "./../components";

interface LandingPageProps {
  articleMetadatas: Components.Type.ArticleMetadata[];
}

const Landing: NextPage<LandingPageProps> = (props: LandingPageProps) => {
  return (
    <div>
      <Head>
        <title>blogcuahuy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <Components.LandingPage.ArticleSection
        articleMetadatas={props.articleMetadatas}
      />

      <div>Landing</div>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const articleMetadatas = await Utilities.LoadAllArticleMetadatas();

  return {
    props: {
      articleMetadatas,
    }, // will be passed to the page component as props
  };
};

export default Landing;
